// CompTIA Security+ SY0-701 — Important Ports & Protocols
const PORT_CATEGORY_OPTIONS=[
  {value:"0",label:"Remote Access & File Transfer"},
  {value:"1",label:"Email Protocols"},
  {value:"2",label:"Web & HTTP"},
  {value:"3",label:"Auth, Directory & AAA"},
  {value:"4",label:"Network Services"},
  {value:"5",label:"File Sharing & Windows"},
  {value:"6",label:"VPN & Tunneling"},
  {value:"7",label:"Databases & Other"},
];
const PORT_CARDS=[
// ── Remote Access & File Transfer ─────────────────────────────
{cat:0,catName:"Remote Access & File Transfer",acr:"20",full:"FTP Data — File Transfer Protocol (data channel)",def:"TCP port 20 carries the actual file data during an active-mode FTP transfer. Port 21 is the control channel. FTP sends everything in cleartext — credentials and data are visible on the wire.\n\nExam note: FTP (20/21) is insecure — replace with SFTP (port 22) or FTPS (port 990).",trick:"20 = data flows; 21 = commands. FTP = Fully Transparent Protocol (no encryption)"},
{cat:0,catName:"Remote Access & File Transfer",acr:"21",full:"FTP Control — File Transfer Protocol (command channel)",def:"TCP port 21 is the FTP command/control channel — login credentials and commands (LIST, GET, PUT) are sent here in cleartext. Port 20 carries data.\n\nExam note: FTP is a classic 'insecure protocol to replace' question. SFTP (22) or FTPS (990/989) are the secure alternatives.",trick:"21 = command channel; 20 = data channel. FTP = Frighteningly Transparent Protocol"},
{cat:0,catName:"Remote Access & File Transfer",acr:"22",full:"SSH / SFTP / SCP — Secure Shell & Secure File Transfer",def:"TCP port 22 is used by SSH (Secure Shell) for encrypted remote command-line access, SFTP (SSH File Transfer Protocol) for encrypted file transfers, and SCP (Secure Copy Protocol) for file copying.\n\nExam note: SSH replaces Telnet (23) and FTP (21). If a question asks for encrypted remote access or secure file transfer, port 22 / SSH is almost always the answer.",trick:"22 = SSH. Think: two swords crossing (2 and 2) = secure duel. SSH = Super Secure Host access"},
{cat:0,catName:"Remote Access & File Transfer",acr:"23",full:"Telnet — Unencrypted Remote Terminal",def:"TCP port 23. Telnet provides remote command-line access but transmits everything — including usernames and passwords — in cleartext.\n\nExam note: Telnet is the textbook 'insecure protocol' example. The secure replacement is SSH (port 22). Any exam scenario mentioning cleartext remote access or legacy network device management points to Telnet.",trick:"23 = Telnet. Think: Telnet = Tell-Net (it tells the network all your secrets in plaintext)"},
{cat:0,catName:"Remote Access & File Transfer",acr:"69",full:"TFTP — Trivial File Transfer Protocol",def:"UDP port 69. TFTP is a simplified, connectionless file transfer protocol with no authentication and no encryption. It is used for bootstrapping devices — sending OS images to routers, switches, and diskless workstations during startup.\n\nExam note: TFTP is always UDP (not TCP), has no login, and is insecure. It is used for PXE boot and network device firmware upgrades, not general file transfer.",trick:"69 = TFTP. 'Trivial' because it is stripped down — no auth, no encryption, UDP only"},
{cat:0,catName:"Remote Access & File Transfer",acr:"3389",full:"RDP — Remote Desktop Protocol",def:"TCP port 3389. RDP allows graphical remote desktop access to Windows systems. It encrypts the session but is a common attack target — brute force, credential stuffing, and BlueKeep exploit.\n\nExam note: RDP on port 3389 exposed to the internet is a major vulnerability. Mitigations include VPN gating, MFA, and NLA (Network Level Authentication). Port 3389 open to the internet is a red flag on any exam scenario.",trick:"3389 = RDP. Think: 3-3-8-9 spells 'DESK' on a phone keypad — Remote DESK top Protocol"},
{cat:0,catName:"Remote Access & File Transfer",acr:"5900",full:"VNC — Virtual Network Computing",def:"TCP port 5900 (base; increments as 5901, 5902, etc. for multiple sessions). VNC provides cross-platform graphical remote desktop access. Many VNC implementations transmit data with weak or no encryption.\n\nExam note: VNC is less common than RDP on the exam but appears in legacy access and insecure remote access scenarios. Prefer SSH tunneling or a VPN when using VNC.",trick:"5900 = VNC. V is the 22nd letter — 22×... just memorize 5900 as 'Five-Nine-Double-Oh, VNC go'"},

// ── Email Protocols ────────────────────────────────────────────
{cat:1,catName:"Email Protocols",acr:"25",full:"SMTP — Simple Mail Transfer Protocol",def:"TCP port 25. SMTP is used by mail servers to relay email between servers (server-to-server delivery). Historically used by clients to send mail, but port 25 is now typically reserved for server-to-server relay and is blocked by most ISPs to prevent spam.\n\nExam note: Port 25 = server-to-server relay. Clients should use port 587 (submission) instead. SMTPS (port 465) uses SSL/TLS.",trick:"25 = SMTP. Simple Mail Transfer. Think: '25 letters in the alphabet minus one' — email almost covers everything"},
{cat:1,catName:"Email Protocols",acr:"110",full:"POP3 — Post Office Protocol v3",def:"TCP port 110. POP3 downloads email from the server to the client, then typically deletes it from the server. No encryption — credentials and email travel in cleartext.\n\nExam note: POP3 (110) = insecure download-and-delete. POP3S (995) = secure version. IMAP (143) keeps mail on the server; IMAPS (993) is the secure version.",trick:"110 = POP3. Pop = mail is POP'd off the server. 110 looks like two mail slots and a mailbox"},
{cat:1,catName:"Email Protocols",acr:"143",full:"IMAP — Internet Message Access Protocol",def:"TCP port 143. IMAP synchronizes email — messages stay on the server, and clients can access them from multiple devices. No encryption in plain IMAP.\n\nExam note: IMAP (143) = sync and keep on server. IMAPS (993) = encrypted version. POP3 (110) = download and delete. If the question mentions accessing email from multiple devices, IMAP is the answer.",trick:"143 = IMAP. I-MAP: you map all your emails across devices. 143 = 'I Love You' — IMAP loves keeping your mail safe on the server"},
{cat:1,catName:"Email Protocols",acr:"465",full:"SMTPS — SMTP over SSL (legacy secure email)",def:"TCP port 465. Originally assigned for SMTP over SSL/TLS (SMTPS). Deprecated by RFC standards in favor of port 587 with STARTTLS, but still widely used by some email clients and servers for implicit TLS.\n\nExam note: 465 = implicit TLS for SMTP (deprecated but still tested). 587 = modern submission with STARTTLS. 25 = server relay.",trick:"465 = SMTPS. Think: 4-6-5 = 'Four-Six-Five, SMTP Lives' with SSL wrapping it"},
{cat:1,catName:"Email Protocols",acr:"587",full:"SMTP Submission — Authenticated email client submission",def:"TCP port 587. The modern standard port for email client-to-server submission (when you send email from your mail client). Uses STARTTLS to upgrade to encrypted communication. Requires authentication.\n\nExam note: 587 = clients submit email. 25 = server-to-server relay. If a question asks which port an email client uses to submit mail securely, the answer is 587.",trick:"587 = SMTP Submission. Think: '587 — Submit By Seven' — your mail client submits on 587"},
{cat:1,catName:"Email Protocols",acr:"993",full:"IMAPS — IMAP over SSL/TLS (secure email sync)",def:"TCP port 993. IMAP with implicit SSL/TLS encryption — the secure version of IMAP. Synchronizes email across devices with the session encrypted from the start.\n\nExam note: 993 = secure IMAP. 143 = plain IMAP. 995 = secure POP3. 110 = plain POP3. Secure versions always have the higher port number.",trick:"993 = IMAPS. '993 — IMAP Secure, three nines means it's fine'"},
{cat:1,catName:"Email Protocols",acr:"995",full:"POP3S — POP3 over SSL/TLS (secure email download)",def:"TCP port 995. POP3 wrapped in SSL/TLS — the secure version of POP3. Downloads and removes email from the server with the session encrypted.\n\nExam note: 995 = secure POP3. 110 = plain POP3. 993 = secure IMAP. 143 = plain IMAP. Pattern: secure email ports are 993 and 995; insecure are 143 and 110.",trick:"995 = POP3S. '995 — POP Securely, five nines for reliability'"},

// ── Web & HTTP ─────────────────────────────────────────────────
{cat:2,catName:"Web & HTTP",acr:"80",full:"HTTP — Hypertext Transfer Protocol",def:"TCP port 80. HTTP is the foundation of web communication — browsers use it to request web pages. All data travels in cleartext, meaning traffic can be intercepted and read.\n\nExam note: HTTP (80) is insecure — no encryption. HTTPS (443) encrypts with TLS. On the exam, HTTP appearing in a scenario where sensitive data is transmitted is always a vulnerability.",trick:"80 = HTTP. Think: 8-0 = 'Eight-Oh, web traffic flow' — the original unencrypted web port"},
{cat:2,catName:"Web & HTTP",acr:"443",full:"HTTPS — HTTP over TLS/SSL",def:"TCP port 443. HTTPS is HTTP encrypted with TLS (Transport Layer Security). The browser verifies the server's certificate before establishing an encrypted session, providing confidentiality, integrity, and server authentication.\n\nExam note: HTTPS (443) = encrypted web. It uses TLS (not SSL — SSL is deprecated). Certificate validation is what makes HTTPS trustworthy.",trick:"443 = HTTPS. Think: 4-4-3 = 'Four-Four-Three, HTTPS protects me' — the secure web port"},
{cat:2,catName:"Web & HTTP",acr:"8080",full:"HTTP Alternate — Web proxy / dev server port",def:"TCP port 8080. Commonly used as an alternate HTTP port for web proxies, development servers, and HTTP traffic that cannot use the privileged port 80.\n\nExam note: Port 8080 often signals a proxy or a non-standard web server. On the exam, web proxy traffic filtering questions may involve port 8080. Admins sometimes try to run HTTP services here to bypass firewall rules blocking port 80.",trick:"8080 = HTTP alternate. Think: 80-80 = port 80 doubled — HTTP but not the standard port"},
{cat:2,catName:"Web & HTTP",acr:"8443",full:"HTTPS Alternate — Alternate HTTPS / management portal",def:"TCP port 8443. An alternate port for HTTPS, commonly used by management interfaces, web application servers (Tomcat), and network device admin portals.\n\nExam note: Port 8443 is HTTPS traffic on a non-standard port. Often appears in questions about management interface security or web application firewalls.",trick:"8443 = HTTPS alternate. Think: 443 with an 8 in front — same secure protocol, different address"},

// ── Auth, Directory & AAA ──────────────────────────────────────
{cat:3,catName:"Auth, Directory & AAA",acr:"88",full:"Kerberos — Network Authentication Protocol",def:"TCP/UDP port 88. Kerberos is the default authentication protocol for Active Directory. Clients obtain a Ticket Granting Ticket (TGT) from the KDC, then exchange it for service tickets — passwords are never sent across the network.\n\nExam note: Port 88 = Kerberos = Active Directory authentication. If a question mentions ticket-based authentication or TGT, the answer is Kerberos on port 88.",trick:"88 = Kerberos. The three-headed dog Cerberus guards the underworld — Kerberos guards the network. 88 looks like a figure-8, like a dog chasing its tail"},
{cat:3,catName:"Auth, Directory & AAA",acr:"389",full:"LDAP — Lightweight Directory Access Protocol",def:"TCP/UDP port 389. LDAP is used to query and modify directory services such as Active Directory and OpenLDAP — retrieving user accounts, group memberships, and attributes. Port 389 LDAP transmits data in cleartext.\n\nExam note: LDAP (389) is insecure. LDAPS (636) is the encrypted version. LDAP is often the answer when a question involves querying a directory service or authenticating against Active Directory.",trick:"389 = LDAP. Think: '389 — LDAP, the directory's key' — phone book protocol for user accounts"},
{cat:3,catName:"Auth, Directory & AAA",acr:"636",full:"LDAPS — LDAP over SSL/TLS",def:"TCP port 636. LDAPS is LDAP wrapped in SSL/TLS, encrypting all directory queries and authentication traffic. It is the secure alternative to plain LDAP on port 389.\n\nExam note: 636 = secure LDAP. 389 = plain LDAP. If a question mentions encrypting directory service traffic or securing Active Directory queries, LDAPS on port 636 is the answer.",trick:"636 = LDAPS. '6-3-6 — LDAP Secured, six-three-six' — secure directory access with TLS wrapping"},
{cat:3,catName:"Auth, Directory & AAA",acr:"1812",full:"RADIUS Authentication — Remote Authentication Dial-In User Service",def:"UDP port 1812. RADIUS is a centralized AAA (Authentication, Authorization, and Accounting) protocol. Port 1812 handles authentication and authorization — the NAS sends user credentials to the RADIUS server, which approves or denies access.\n\nExam note: 1812 = RADIUS auth. 1813 = RADIUS accounting. RADIUS is used for Wi-Fi enterprise authentication (WPA2/WPA3-Enterprise) and VPN authentication.",trick:"1812 = RADIUS auth. Think: 1812 War — the battle to authenticate who gets in"},
{cat:3,catName:"Auth, Directory & AAA",acr:"1813",full:"RADIUS Accounting — Remote Authentication Dial-In User Service",def:"UDP port 1813. The RADIUS accounting port — after authentication (port 1812), the RADIUS server logs session details: who connected, when, for how long, and what they accessed.\n\nExam note: 1812 = RADIUS authentication. 1813 = RADIUS accounting (logging). Together they implement the 'Authentication, Authorization, and Accounting' (AAA) model.",trick:"1813 = RADIUS accounting. Think: 1812 (auth) + 1 more year = 1813 for accounting the session details"},

// ── Network Services ───────────────────────────────────────────
{cat:4,catName:"Network Services",acr:"53",full:"DNS — Domain Name System",def:"TCP/UDP port 53. DNS translates human-readable domain names (google.com) into IP addresses. UDP port 53 is used for standard queries; TCP port 53 is used for zone transfers and large responses.\n\nExam note: DNS (53) is a frequent attack target — DNS poisoning, DNS tunneling, and DNS amplification attacks all use port 53. DNS over HTTPS (DoH) and DNS over TLS (DoT) are encrypted alternatives.",trick:"53 = DNS. Think: 5-3 = 'Fifty-Three, DNS answers me' — your phone book for the internet"},
{cat:4,catName:"Network Services",acr:"67",full:"DHCP Server — Dynamic Host Configuration Protocol (server)",def:"UDP port 67. The DHCP server listens on port 67. When a client broadcasts a DHCPDISCOVER, the server responds on port 67, offering an IP address, subnet mask, gateway, and DNS server.\n\nExam note: 67 = DHCP server receives. 68 = DHCP client receives. DHCP attacks include rogue DHCP servers and DHCP starvation (exhausting the address pool). DHCP snooping is the defense.",trick:"67 = DHCP Server. '67 — Server waits for you.' 68 = client. Server is 67, client is 68 (one higher)"},
{cat:4,catName:"Network Services",acr:"68",full:"DHCP Client — Dynamic Host Configuration Protocol (client)",def:"UDP port 68. The DHCP client receives configuration from the server on port 68. The client broadcasts a DHCPDISCOVER, and the DHCP server sends its offer to port 68 on the client.\n\nExam note: 67 = DHCP server. 68 = DHCP client. Both use UDP broadcast. DHCP snooping on switches prevents rogue DHCP server attacks by only allowing DHCP offers from trusted ports.",trick:"68 = DHCP Client. '68 — Client waits on you.' Server is 67, client is 68 (one step above)"},
{cat:4,catName:"Network Services",acr:"123",full:"NTP — Network Time Protocol",def:"UDP port 123. NTP synchronizes clocks across networked devices. Accurate time is critical for security — authentication protocols (Kerberos), log correlation, and certificate validation all depend on synchronized clocks.\n\nExam note: NTP (123) is commonly tested in the context of Kerberos (which requires clocks within 5 minutes) and log correlation for incident response. NTP amplification is a DDoS attack vector.",trick:"123 = NTP. Think: 1-2-3 like counting seconds — Network Time Protocol counts time for everyone"},
{cat:4,catName:"Network Services",acr:"161",full:"SNMP — Simple Network Management Protocol (polling)",def:"UDP port 161. SNMP is used by management stations to poll network devices (routers, switches, servers) for status and performance data. SNMPv1 and SNMPv2c use community strings (essentially plaintext passwords). SNMPv3 adds authentication and encryption.\n\nExam note: SNMP (161) polls; SNMP Trap (162) pushes alerts. Use SNMPv3 — earlier versions send community strings in cleartext and are vulnerable to sniffing.",trick:"161 = SNMP poll. Think: '1-6-1, SNMP asks — is everything fine?' Polling = asking the device"},
{cat:4,catName:"Network Services",acr:"162",full:"SNMP Trap — Simple Network Management Protocol (alerts)",def:"UDP port 162. SNMP Trap messages are unsolicited alerts sent from network devices to a management station when an event occurs (interface down, CPU spike, fan failure). The device pushes the alert rather than waiting to be polled.\n\nExam note: 161 = management station polls device. 162 = device pushes trap alert to management station. SNMPv3 traps include authentication and privacy.",trick:"162 = SNMP Trap. Think: '162, the trap springs' — the device alerts YOU instead of waiting to be asked"},
{cat:4,catName:"Network Services",acr:"514",full:"Syslog — System Logging Protocol (cleartext)",def:"UDP port 514. Syslog is the standard protocol for forwarding log messages from devices (firewalls, servers, routers) to a centralized log server or SIEM. Plain syslog on 514 is unencrypted and uses UDP (best-effort delivery).\n\nExam note: Syslog (514) = cleartext, UDP, unreliable. Syslog over TLS (6514) = encrypted, TCP, reliable. On the exam, if a question asks about securing log forwarding, the answer is TLS on port 6514.",trick:"514 = Syslog. Think: '514 — Syslog sends it raw' — all your logs flying through the wire in plaintext"},
{cat:4,catName:"Network Services",acr:"6514",full:"Syslog over TLS — Encrypted log forwarding",def:"TCP port 6514. Syslog over TLS uses TCP (reliable delivery) and TLS encryption to secure log forwarding — preventing log tampering and eavesdropping in transit.\n\nExam note: 514 = plain syslog (UDP, cleartext). 6514 = secure syslog (TCP, TLS). If a question asks how to protect log integrity in transit or secure a SIEM log feed, port 6514 with TLS is the answer.",trick:"6514 = Syslog TLS. '6514 — six-five-one-four, logs locked and secured' — add TLS to syslog"},

// ── File Sharing & Windows Services ───────────────────────────
{cat:5,catName:"File Sharing & Windows Services",acr:"137",full:"NetBIOS Name Service — Windows name resolution",def:"UDP port 137. NetBIOS Name Service (NBNS) resolves NetBIOS names to IP addresses on Windows networks — similar to DNS but for older Windows naming. Used in legacy Windows environments.\n\nExam note: NetBIOS ports (137, 138, 139) are associated with LLMNR/NBNS poisoning attacks, where an attacker responds to broadcast name resolution queries to capture NTLMv2 hashes. Disable NetBIOS when not needed.",trick:"137 = NetBIOS Name Service. '137 — Names resolved here.' The trio: 137 (names), 138 (data), 139 (sessions)"},
{cat:5,catName:"File Sharing & Windows Services",acr:"138",full:"NetBIOS Datagram Service — Windows broadcast messaging",def:"UDP port 138. NetBIOS Datagram Service carries connectionless broadcast and multicast messages in Windows networks — used for browser service announcements.\n\nExam note: Part of the NetBIOS trio (137, 138, 139). Modern Windows prefers DNS and SMB over TCP/IP directly. NetBIOS datagram traffic is a legacy protocol that can leak network information.",trick:"138 = NetBIOS Datagrams. '138 — Data drifts by.' 137 (names), 138 (datagrams), 139 (sessions)"},
{cat:5,catName:"File Sharing & Windows Services",acr:"139",full:"NetBIOS Session Service — Windows file sharing (legacy)",def:"TCP port 139. NetBIOS Session Service provides connection-oriented communication for Windows file and printer sharing over older networks. Largely replaced by SMB on port 445 (direct hosting).\n\nExam note: Port 139 = SMB over NetBIOS (older method). Port 445 = SMB direct (modern method). Both are used for Windows file sharing. Blocking 139 and 445 prevents SMB-based attacks like WannaCry/EternalBlue.",trick:"139 = NetBIOS Session. '139 — Sessions start here.' 139 is the older SMB door; 445 is the newer one"},
{cat:5,catName:"File Sharing & Windows Services",acr:"445",full:"SMB — Server Message Block (Windows file sharing)",def:"TCP port 445. SMB (Server Message Block) is used for Windows file sharing, printer sharing, and inter-process communication. SMB direct over port 445 replaced the older NetBIOS (139) method.\n\nExam note: Port 445 is associated with major exploits — EternalBlue (MS17-010) enabled WannaCry ransomware to spread via SMB. SMBv1 is critically insecure. Block 445 at perimeter firewalls and disable SMBv1.",trick:"445 = SMB. Think: 4-4-5 = 'SMB files fly' — Windows shares everything over 445. WannaCry loved this port"},
{cat:5,catName:"File Sharing & Windows Services",acr:"2049",full:"NFS — Network File System",def:"TCP/UDP port 2049. NFS allows Unix/Linux systems to share file systems over a network, mounting remote directories as if they were local. NFS security relies on proper export controls and host-based access lists.\n\nExam note: NFS (2049) appears in Linux/Unix file sharing scenarios. NFS v4 uses TCP and includes stronger security. NFSv3 and earlier can be vulnerable to unauthorized mounting if misconfigured.",trick:"2049 = NFS. Think: '2049 — Like the movie, it is the future of file sharing' (Blade Runner 2049)"},
{cat:5,catName:"File Sharing & Windows Services",acr:"135",full:"RPC — Remote Procedure Call (Windows DCOM)",def:"TCP port 135. Windows RPC Endpoint Mapper — clients query port 135 to find the dynamic port for a specific RPC-based service (DCOM, WMI, MSRPC). The actual service then uses a high dynamic port.\n\nExam note: Port 135 is the entry point for Windows RPC services. It was exploited by the Blaster worm (MS03-026). Blocking or limiting port 135 reduces Windows attack surface.",trick:"135 = RPC. Think: '135 — RPC is the switchboard operator' — you ask 135 which port to call next"},

// ── VPN & Tunneling ────────────────────────────────────────────
{cat:6,catName:"VPN & Tunneling",acr:"500",full:"IKE / ISAKMP — IPSec VPN key exchange",def:"UDP port 500. IKE (Internet Key Exchange) / ISAKMP is used to negotiate and establish IPSec VPN tunnels — authenticating peers and negotiating encryption parameters.\n\nExam note: Port 500 = IKE for IPSec VPNs. When IPSec traffic passes through NAT, port 4500 (NAT-T) is used instead. If a question mentions site-to-site VPN or IPSec tunnel setup, port 500 is the answer.",trick:"500 = IKE/IPSec. Think: '500 keys in a VPN lockbox' — IKE handles the key exchange for IPSec"},
{cat:6,catName:"VPN & Tunneling",acr:"4500",full:"NAT-T — IPSec through NAT (NAT Traversal)",def:"UDP port 4500. NAT Traversal (NAT-T) allows IPSec traffic to pass through NAT devices. When the IKE negotiation on port 500 detects a NAT device, both endpoints switch to port 4500 and encapsulate ESP packets in UDP.\n\nExam note: Port 4500 = IPSec behind NAT. Port 500 = standard IKE. If a site-to-site VPN fails because of NAT, enabling NAT-T (port 4500) is the fix.",trick:"4500 = NAT-T. Think: '4500 — IPSec got translated' — when your VPN hits a NAT, move to 4500"},
{cat:6,catName:"VPN & Tunneling",acr:"1723",full:"PPTP — Point-to-Point Tunneling Protocol (insecure VPN)",def:"TCP port 1723. PPTP is an older VPN protocol that is now considered cryptographically broken — MS-CHAPv2 can be cracked offline. PPTP is fast but insecure.\n\nExam note: PPTP (1723) = insecure VPN. On any exam question asking which VPN protocol to avoid or which is vulnerable, PPTP is the answer. Modern replacements include L2TP/IPSec, SSTP, OpenVPN, and IKEv2/IPSec.",trick:"1723 = PPTP. Think: '1723 — ancient VPN, cracked and gone' — PPTP is the Telnet of VPN protocols"},
{cat:6,catName:"VPN & Tunneling",acr:"1701",full:"L2TP — Layer 2 Tunneling Protocol",def:"UDP port 1701. L2TP by itself provides no encryption. It is almost always paired with IPSec (L2TP/IPSec) to provide a secure VPN tunnel. L2TP creates the tunnel; IPSec provides authentication and encryption.\n\nExam note: L2TP alone = no encryption. L2TP/IPSec = secure VPN. Port 1701 is used for L2TP; IPSec uses ports 500 (IKE) and 4500 (NAT-T). PPTP (1723) is less secure than L2TP/IPSec.",trick:"1701 = L2TP. Think: 'L2TP — Layer 2 Tunnels Passively' without IPSec it has no security"},

// ── Databases & Other ──────────────────────────────────────────
{cat:7,catName:"Databases & Other",acr:"1433",full:"MSSQL — Microsoft SQL Server",def:"TCP port 1433. Microsoft SQL Server listens on port 1433 by default. Direct internet exposure of port 1433 is a major risk — SQL injection and brute-force attacks are common.\n\nExam note: Port 1433 = MSSQL. In exam scenarios about database hardening or SQL injection attack surface, port 1433 is the answer. Never expose 1433 directly to the internet.",trick:"1433 = MSSQL. Think: '1-4-3-3 — SQL Server, open the door.' 1433 is the Microsoft SQL front door"},
{cat:7,catName:"Databases & Other",acr:"3306",full:"MySQL — MySQL Database Server",def:"TCP port 3306. MySQL database server default port. Like MSSQL, exposing port 3306 to the internet is dangerous — SQL injection and unauthorized access are primary risks.\n\nExam note: 3306 = MySQL. 1433 = MSSQL. 5432 = PostgreSQL. Database ports should be firewalled and only accessible from application servers, never from the internet.",trick:"3306 = MySQL. Think: '33-06 — MySQL, let it through' — the open-source database's door"},
{cat:7,catName:"Databases & Other",acr:"5060",full:"SIP — Session Initiation Protocol (VoIP, cleartext)",def:"TCP/UDP port 5060. SIP is the signaling protocol for VoIP calls — it sets up, maintains, and tears down voice and video calls. Plain SIP transmits call metadata in cleartext.\n\nExam note: 5060 = SIP (cleartext). 5061 = SIPS (SIP over TLS). VoIP security concerns include call eavesdropping, toll fraud, and SIP injection. Use SIPS (5061) and SRTP for encrypted VoIP.",trick:"5060 = SIP. Think: '5060 — SIP a call, but it is not encrypted.' 5060 is the VoIP dialtone"},
{cat:7,catName:"Databases & Other",acr:"5061",full:"SIPS — SIP over TLS (secure VoIP signaling)",def:"TCP port 5061. SIPS is SIP with TLS encryption for VoIP call signaling — protecting call setup metadata from eavesdropping. SIPS (5061) + SRTP (Secure RTP) together provide fully encrypted VoIP.\n\nExam note: 5060 = SIP (cleartext). 5061 = SIPS (encrypted signaling). SRTP encrypts the actual voice data. If a question asks how to secure VoIP, the answer involves SIPS (5061) and SRTP.",trick:"5061 = SIPS. '5060 + 1 = 5061 — add TLS to SIP and you get SIPS, secure VoIP signaling'"},
{cat:7,catName:"Databases & Other",acr:"119",full:"NNTP — Network News Transfer Protocol",def:"TCP port 119. NNTP is used to transfer newsgroup articles (Usenet) between servers and to clients. Largely obsolete but occasionally appears on CompTIA exams as a legacy protocol.\n\nExam note: Port 119 = NNTP (Usenet news). Rarely tested but included in CompTIA port lists. Remember it as the 'news' protocol.",trick:"119 = NNTP. Think: '119 — News at eleven' (like 11-9 emergency news). NNTP = Network News"},
];
